services:
  # MongoDB
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]

  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Node backend
  backend:
    build: ./backend
    restart: unless-stopped
    command: npm run start 
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./backend:/usr/src/app
      - node_modules_cache:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/MyCourses
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - mongo
      - redis

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /home/myubuntu/docker-data/MyCourses/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  node_modules_cache:
  mongo_data:
  redis_data:
