services:
  # MongoDB
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./docker-data/MyCourses/mongo:/data/db

  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/MyCourses/redis:/data

  # Node backend
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - node_modules_cache:/usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mycourses
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker-data/MyCourses/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  node_modules_cache:
